import win32inet

INTERNET_OPTION_SETTINGS_CHANGED = 0x000027
INTERNET_OPTION_REFRESH = 0x000025

win32inet.InternetSetOption(0, INTERNET_OPTION_SETTINGS_CHANGED, None)
win32inet.InternetSetOption(0, INTERNET_OPTION_REFRESH, None)
